/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/**
 * Test configuration helper
 * This provides a minimal valid configuration for running tests without requiring
 * a real GCP project or the testconfig.json file generated by deploy.sh
 */

module.exports = {
  gcpConfig: {
    projectId: "test-project-12345",
    location: "us-central1",
    bigQuery: {
      datasetId: "dicom",
      instancesTableId: "instances",
    },
    embedding: {
      input: {
        gcsBucketPath: "gs://test-bucket/extract",
        summarizeText: {
          model: "gemini-2.5-flash-lite",
          maxLength: 1024,
        },
        vector: {
          model: "multimodalembedding@001",
        },
      },
    },
  },
  dicomParser: {},
  jsonOutput: {
    useArrayWithSingleValue: false,
    ignoreGroupLength: true,
    ignoreMetaHeader: false,
    ignorePrivate: false,
    ignoreBinary: false,
    useCommonNames: true,
    explicitBulkDataRoot: false,
  },
  src: "TEST",
};
