// Events from https://cloud.google.com/storage/docs/pubsub-notifications#events
const GCS_OBJ_ARCHIVE = "OBJECT_ARCHIVE";
const GCS_OBJ_DELETE = "OBJECT_DELETE";
const GCS_OBJ_FINALIZE = "OBJECT_FINALIZE";
const GCS_OBJ_METADATA_UPDATE = "OBJECT_METADATA_UPDATE";
const GCS_EVENT_TYPES = [GCS_OBJ_ARCHIVE, GCS_OBJ_DELETE, GCS_OBJ_FINALIZE, GCS_OBJ_METADATA_UPDATE];

const HCAPI_FINALIZE = "HCAPI_FINALIZE";
const HCAPI_EVENT_TYPES = [HCAPI_FINALIZE];

const GCS_PUBSUB_MSG_V1 = "JSON_API_V1";
const GCS_PUBSUB_UNWRAP = "GCS_PUBSUB_UNWRAP";
const HCAPI_PUBSUB_UNWRAP = "HCAPI_PUBSUB_UNWRAP";
const EVENT_HANDLER_NAMES = [GCS_PUBSUB_UNWRAP, HCAPI_PUBSUB_UNWRAP];

const STORAGE_TYPE_GCS = "GCS";
const STORAGE_TYPE_DICOMWEB = "HCAPI_DICOM";

module.exports = {
  GCS_OBJ_ARCHIVE,
  GCS_OBJ_DELETE,
  GCS_OBJ_FINALIZE,
  GCS_OBJ_METADATA_UPDATE,
  GCS_EVENT_TYPES,
  GCS_PUBSUB_UNWRAP,
  HCAPI_FINALIZE,
  HCAPI_EVENT_TYPES,
  HCAPI_PUBSUB_UNWRAP,
  EVENT_HANDLER_NAMES,
  STORAGE_TYPE_GCS,
  STORAGE_TYPE_DICOMWEB,
  GCS_PUBSUB_MSG_V1,
};
